baseurl: "/"
title: "Stackbit DIY Theme"
init_is: "js/init.js"
page_load_js: "js/page-load.js"
page_unload_js: "js/page-unload.js"
params:
  description: A "do it yourself" theme for Stackbit
  layout: full-width
  style: minimal
  palette: blue
  mode: light
  base_font: sans-serif
  header:
    title: DIY
    logo: "images/logo.svg"
    has_primary_nav: true
    primary_nav_links:
      - label: Pricing
        url: /pricing
        style: link
      - label: About
        url: /about
        style: link
      - label: Blog
        url: /blog
        style: link
      - label: Style Guide
        url: /style-guide
        style: link
    has_secondary_nav: true
    secondary_nav_links:
      - label: App Store
        url: /pricing
        style: primary
      - label: Google Play
        url: /pricing
        style: secondary
    has_anncmnt: true
    anncmnt_content: >-
      Curabitur ac tellus mattis, tempor ipsum eu, eleifend sapien. **[Learn More](/pricing/)**
    anncmnt_align: left
    anncmnt_is_home_only: true
    anncmnt_has_close: true
    anncmnt_id: new-features
  footer:
    logo: "images/logo.svg"
    has_primary_nav: true
    primary_nav_title: Company
    primary_nav_links:
      - label: About
        url: /about
        style: link
      - label: Style Guide
        url: /style-guide
        style: link
    has_secondary_nav: true
    secondary_nav_title: Blog
    secondary_nav_links:
      - label: News
        url: /blog/category/news
        style: link
      - label: General
        url: /blog/category/general
        style: link
      - label: Tutorials
        url: /blog/category/tutorials
        style: link
    has_tertiary_nav: true
    tertiary_nav_title: Legal
    tertiary_nav_links:
      - label: Terms & Conditions
        url: /terms-conditions
        style: link
      - label: Privacy Policy
        url: /privacy-policy
        style: link
    has_social: true
    social_links:
      - label: Twitter
        url: https://twitter.com/
        style: link
        has_icon: true
        icon: twitter
        icon_position: center
        new_window: true
      - label: GitHub
        url: https://github.com/
        style: link
        has_icon: true
        icon: github
        icon_position: center
        new_window: true
      - label: LinkedIn
        url: https://www.linkedin.com/
        style: link
        has_icon: true
        icon: linkedin
        icon_position: center
        new_window: true
      - label: LinkedIn
        url: https://www.youtube.com/
        style: link
        has_icon: true
        icon: youtube
        icon_position: center
        new_window: true
      - label: LinkedIn
        url: https://vimeo.com/
        style: link
        has_icon: true
        icon: vimeo
        icon_position: center
        new_window: true
    content: "&copy; Stackbit-DIY. All rights reserved."
    links:
      - label: Made with Stackbit.
        url: https://www.stackbit.com
        style: link
sass:
  input_file: sass/main.scss
  output_file: css/main.css
  indentWidth: 4
  outputStyle: expanded
  precision: 10
templates:
  body_class: "layout-{{ site.params.layout }} style-{{ site.params.style }} palette-{{ site.params.palette }} mode-{{ site.params.mode }} font-{{ site.params.base_font }}"